### ISSUE TITLE
What is this font?

### ISSUE THREAD

**Issue by rediffusion** [EliverLara/sweet-vscode-icons#1]
✋ Hi bro, first of all 10x for your icons I really appreciate it! Can you tell me what is this font on the picture? 
___

![image](https://user-images.githubusercontent.com/30071027/76338456-c3429e80-6309-11ea-8c20-a134cf66fae0.png)

**Comment by EliverLara** [comment]
Hi, the font I use is [operator mono](https://www.cufonfonts.com/font/operator-mono).
